name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]   # Runs on push to main
  pull_request:
    branches: [ "main" ]   # Runs for PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 4. Run Tests
      - name: Run Tests
        run: mvn test

      # 5. Package Artifact
      - name: Package JAR
        run: mvn package -DskipTests

      # 6. Upload JAR as GitHub Artifact
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar
